### ISSUE TITLE
Plesk Cgroups

### ISSUE THREAD

**Issue by Andrea-LS** [layershift/kb-layershift#16]
# Summary

What the Cgroups manager is, setting limits, managing notifications - anything else deemed important from a support pov.
# References

[List of known authoritative links addressing this topic (e.g. vendor / project documentation). These may form a starting point for any research but must not be copied verbatim.](https://docs.plesk.com/en-US/obsidian/administrator-guide/plesk-administration/plesk-for-linux-cgroups-manager.78308/)

**Comment by rauladorean** [comment]
https://www.layershift.com/kb/managed-vps/plesk/plesk-cgroups-manager
